version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: run tests
          command: |
            python test.py

      - store_artifacts:
          path: test-reports
          destination: test-reports
  release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install --save-dev semantic-release
      - run: npx semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - build
      - release:
          requires:
            - build
